### ISSUE TITLE
default node['authorization']['sudo']['passwordless'] is ignored

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/sudo#98]
### Cookbook version
3.3.1

### Chef-client version
12.18.31

### Platform Details
Test Kitchen running rhel6 image in openstack

### Scenario:
Test Kitchen configuration includes:

```
suites:
  - name: sudo
    run_list:
      - recipe[minitest-handler]
      - recipe[sudo]
```

### Steps to Reproduce:
Run the above suite in Test Kitchen without setting any other defaults or overrides. This sets up the sudo::default recipe run with all cookbook defaults.

### Expected Result:
/etc/sudoers should include a configuration for the %sysadmin group and NOPASSWD is not present.
```
%sysadmin ALL=(ALL)  ALL
```

### Actual Result:
/etc/sudoers is changed to have these lines:
```
           +# Members of the group 'sysadmin' may gain root privileges
           +%sysadmin ALL=(ALL) NOPASSWD:ALL
```

Only when the attribute is set at a higher precedence does it render the right line in /etc/sudoers. For example, configure Test Kitchen, like this and it renders correctly:
```
suites:
  - name: sudo
    run_list:
      - recipe[minitest-handler]
      - recipe[sudo]
    attributes:
      authorization:
        sudo:
          passwordless: false
```
